name: bible_ai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  delightful_toast: ^1.1.0
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0


flutter_gen:
    output: lib/gen/ # Optional (default: lib/gen/)
    line_length: 80 # Optional (default: 80)

    # Optional
    integrations:
      image: true
      flutter_svg: true
      rive: true
      lottie: true



flutter:
  uses-material-design: true

  assets:
    - assets/
#    - assets/abraham.png
#    - assets/google.png
#    - assets/apple.png
#    - assets/congratulations.png
#    - assets/bible.png
#    - assets/bible_white.png
#    - assets/img.png
#    - assets/notification.png
#    - assets/paywall_background.png
#    - assets/profile.png
#    - assets/welcome.png


#
